"""transações volta a ser guardado como decimal

Revision ID: 5e06fe93b369
Revises: ee8840a8bc67
Create Date: 2026-05-31 02:13:36.057413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5e06fe93b369"
down_revision: Union[str, Sequence[str], None] = "ee8840a8bc67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.alter_column(
            "amount",
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_type=sa.Integer(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.DECIMAL(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
