"""Updated tables to int

Revision ID: ee8840a8bc67
Revises: 91573322fa10
Create Date: 2026-05-30 23:42:40.275442

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ee8840a8bc67"
down_revision: Union[str, Sequence[str], None] = "91573322fa10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table("accounts") as batch_op:
        batch_op.alter_column(
            "balance",
            type_=sa.Integer(),
            existing_type=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=False,
        )
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.alter_column(
            "amount",
            type_=sa.Integer(),
            existing_type=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts") as batch_op:
        batch_op.alter_column(
            "balance",
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_type=sa.Integer(),
            existing_nullable=False,
        )
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.alter_column(
            "amount",
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_type=sa.Integer(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
